server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCB
                fallbackUri: forward:/fallback/users
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notify/**
          filters:
            - name: CircuitBreaker
              args:
                name: notificationServiceCB
                fallbackUri: forward:/fallback/notify

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/